services:
  mongodb:
    image: "mongo"  

  ludoclient:
    build:
      context: ./ludoClient
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - /src/app/ludo/node_modules
      - ./ludoclient:/src/app/ludo

  authserver:
    build:
      context: ./authserver
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes: 
      - /src/app/authserver/node_modules
      - ./authserver:/src/app/authserver       

  ludoserver:
    build:
      context: ./ludoserver
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /src/app/ludoserver/node_modules
      - ./ludoserver:/src/app/ludoserver  
